### ISSUE TITLE
NorthstarProton not launching origin

### ISSUE THREAD

**Issue by jpechg** [cyrv6737/NorthstarProton#1] opened 2022-09-05 14:41 UTC
When the play button is clicked on steam, nothing appears on the screen and the game does not start, but when proton experimental is used, the origin window pops up before the game is launched

**Comment by cyrv6737** [comment] 2022-09-06 00:33
Please add `PROTON_LOG=1 %command%` to your TF|2 launch options, run the game, then send the log file that is generated in your home directory.

Also please post the output of `ldd --version`, as I suspect you probably have an outdated glibc.

**Comment by jpechg** [comment] 2022-09-06 08:41
the log:
[steam-1237970.log](https://github.com/cyrv6737/NorthstarProton/files/9494887/steam-1237970.log)
output of ldd --version:
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35

**Comment by begin-theadventure** [comment] 2022-09-06 08:52
gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded
Maybe it has to do with the Steam overlay?
Have you tried to turn it off?

**Comment by jpechg** [comment] 2022-09-06 08:57
Yes, this is one of the things I tried before opening the issue, and it does not change the errors on the log at all

**Comment by cyrv6737** [comment] 2022-09-17 06:53
@jpechg Please try the latest build and see if that changes anything on your end.

**Comment by pinusc** [comment] 2022-10-13 18:36
I have been encountering the same bug. Latest NorthstarProton and Northstar, updated today (although I first tried a few weeks ago with whatever version was available then, and it also did not work)

Launching TF2 without NorthStarProton works as expected, origin opens in the background and then the game launches (without northstar, obviously). 

Log file: [steam-1237970.log](https://termbin.com/3jg4)

`ldd --version` shows 2.33

**Comment by cyrv6737** [comment] 2022-10-13 18:56
@pinusc Please go to settings -> developer -> delete proton files, then relaunch the game with NorthstarProton.
This is assuming you're using the SteamDeck UI and not desktop mode btw.

**Comment by pinusc** [comment] 2022-10-13 20:38
> @pinusc Please go to settings -> developer -> delete proton files, then relaunch the game with NorthstarProton. This is assuming you're using the SteamDeck UI and not desktop mode btw.

Just tried this, did not fix the issue

**Comment by cyrv6737** [comment] 2022-10-13 23:40
@pinusc 
1) Verify integrity of Titanfall 2 through steam
2) Reinstall Northstar
3) Reinstall NorthstarProton

I confirmed earlier that NorthstarProton still works on Deck. In theory if it works on one Deck, it should work on all of them I'm unsure why yours isn't working.

Some things to check:
- Can you better describe the behavior you're experiencing? 
- Are you force-closing the game or does it hard crash? 
- Have you made any modifications to your Deck? 
- Is your Deck up to date?

**Comment by cyrv6737** [comment] 2022-10-31 20:01
I'm closing this issue because Origin is no longer used with EA games on Steam. I recommend doing the following:

- Delete your compatdata for titanfall 2
- Install `d3dcompiler_47`, `d3dcompiler_43`, `d3dx9`, and `corefonts` with protontricks
- Launch the game

**Closed as completed by cyrv6737** 2022-10-31 20:01 UTC
Labels: ubuntu
