### ISSUE TITLE
Can't connect to any server (Steam Deck)

### ISSUE THREAD

**Issue by aidinzolghadr** [cyrv6737/NorthstarProton#14] opened 2023-09-14 00:46 UTC
Hi,

As the title says I can't connect to any server, I installed the latest version via Proton-Qt. I'm testing on Steam Deck. I don't know if this is relevant but I noticed Custom Server in description of all the maps, is this the case and if yes, how to fix it?

Thanks

**Comment by cyrv6737** [comment] 2023-10-19 02:14
We've recently gone under a large overhaul for NorthstarProton. Your issue should not have been caused by the proton build itself, but do give the newest release a try if you are still experiencing problems. I'm going to close this issue as it relates to the legacy NorthstarProton. Feel free to open another one or ask for help in our Discord.

**Closed as completed by cyrv6737** 2023-10-19 02:14 UTC
